export const getClothes = () => [
  {
    image: "images/women_clothes/pants1.png",
    name: "grey pants",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/women_clothes/pants2.png",
    name: "grey&black pants",
    price: "$20.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/pants3.png",
    name: "dark-grey pants",
    price: "$20.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/pants4.png",
    name: "black pants",
    price: "$16.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/pants5.png",
    name: "purple pants",
    price: "$18.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/pants6.png",
    name: "blue pants",
    price: "$20.99",
    discountPrice: "$14.99",
  },
  {
    image: "images/women_clothes/top1.png",
    name: "dark-grey t-shirt",
    price: "$12.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top2.png",
    name: "white t-shirt",
    price: "$11.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top3.png",
    name: "black t-shirt",
    price: "$16.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top4.png",
    name: "blue top",
    price: "$9.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top5.png",
    name: "grey t-shirt",
    price: "$10.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top6.png",
    name: "yellow top",
    price: "$9.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top7.png",
    name: "tight t-shirt",
    price: "$10.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top8.png",
    name: "green t-shirt",
    price: "$12.99",
    discountPrice: false,
  },
  {
    image: "images/women_clothes/top9.png",
    name: "dark hoodie",
    price: "$20.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/pants1.png",
    name: "grey pants",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/men_clothes/pants2.png",
    name: "black pants",
    price: "$16.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/pants3.png",
    name: "dark-grey pants",
    price: "$20.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/pants4.png",
    name: "blue pants",
    price: "$17.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/pants5.png",
    name: "dark-grey pants",
    price: "$14.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/top1.png",
    name: "black top",
    price: "$13.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/top2.png",
    name: "blue top",
    price: "$20.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/top3.png",
    name: "white top",
    price: "$13.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/top4.png",
    name: "tight t-shirt",
    price: "$15.99",
    discountPrice: false,
  },
  {
    image: "images/men_clothes/top5.png",
    name: "grey top",
    price: "$20.99",
    discountPrice: false,
  },
];
