export const getSupplements = () => [
  {
    image: "images/protein/menu-1.png",
    name: "Whey protein 2kg",
    price: "$30.99",
    discountPrice: false,
  },
  {
    image: "images/protein/menu-2.png",
    name: "vegan protein 1kg",
    price: "$30.99",
    discountPrice: "$17.99",
  },
  {
    image: "images/protein/menu-3.png",
    name: "pure protein vanilla 3kg",
    price: "$30.99",
    discountPrice: "$17.99",
  },
  {
    image: "images/protein/menu-4.png",
    name: "Elite whey 1kg",
    price: "$27.99",
    discountPrice: "$19.99",
  },
  {
    image: "images/protein/menu-5.png",
    name: "gold standard 1kg",
    price: "$49.99",
    discountPrice: false,
  },
  {
    image: "images/protein/menu-6.png",
    name: "Isolate Soy 1kg",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/protein/menu-7.png",
    name: "Vegetal 2kg",
    price: "$23.99",
    discountPrice: false,
  },
  {
    image: "images/creatine/c-1.png",
    name: "pure creatine 0.5kg",
    price: "$20.99",
    discountPrice: "$12.99",
  },
  {
    image: "images/creatine/c-2.png",
    name: "creatine monohydrate 0.5kg",
    price: "$20.99",
    discountPrice: "$12.99",
  },
  {
    image: "images/creatine/c-3.png",
    name: "universal creatine 0.5kg",
    price: "$13.99",
    discountPrice: false,
  },
  {
    image: "images/creatine/c-4.png",
    name: "creatine monohydrate 0.5kg",
    price: "$20.99",
    discountPrice: "$12.99",
  },
  {
    image: "images/creatine/c-5.png",
    name: "100% creatine monohydrate",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/creatine/c-6.png",
    name: "platinum creatine 1kg",
    price: "$16.99",
    discountPrice: false,
  },
  {
    image: "images/gainers/g-1.png",
    name: "mass gainer 2kg",
    price: "$30.99",
    discountPrice: "$25.99",
  },
  {
    image: "images/gainers/g-2.png",
    name: "Choko gainer 5kg",
    price: "$70.99",
    discountPrice: "$40.99",
  },
  {
    image: "images/gainers/g-3.png",
    name: "N-mass 10kg",
    price: "$200.99",
    discountPrice: "$99.99",
  },
  {
    image: "images/gainers/g-4.png",
    name: "mass gain 3kg",
    price: "$20.99",
    discountPrice: false,
  },
  {
    image: "images/gainers/g-5.png",
    name: "vanilla gainer 5kg",
    price: "$35.99",
    discountPrice: false,
  },
  {
    image: "images/gainers/g-6.png",
    name: "Mass boost 2kg",
    price: "$23.99",
    discountPrice: "$18.99",
  },
  {
    image: "images/bcaa/bca-1.png",
    name: "bcaa 11:3",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/bcaa/bca-2.png",
    name: "bcaa strawberry",
    price: "$20.99",
    discountPrice: "15.99",
  },
  {
    image: "images/bcaa/bca-3.png",
    name: "bcaa watermelon",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/bcaa/bca-4.png",
    name: "bcaa forestMix",
    price: "$20.99",
    discountPrice: "$15.99",
  },
  {
    image: "images/bcaa/bca-5.png",
    name: "bcaa extended",
    price: "$20.99",
    discountPrice: "$16.99",
  },
  {
    image: "images/bcaa/bca-6.png",
    name: "bcaa tablets",
    price: "$20.99",
    discountPrice: "$11.99",
  },
];
